### ISSUE TITLE
select does not expand outside card

### ISSUE THREAD

**Issue by ArjanM83** [MEYVN-digital/mdl-selectfield#1]
The select box does not expand outside the card where it's based on.

See my screenshot with first the select closed, on a grey card.
Then see the select opened but not expanded over the grey card.

![select](https://cloud.githubusercontent.com/assets/7382294/11345331/82d8b9b0-9216-11e5-810f-e9b3f2aae048.png)

**Comment by zetta83** [comment]
Yes, because the `.mdl-card` contains a property `overflow: hidden;`
[src/card/_card.scss](https://github.com/google/material-design-lite/blob/master/src/card/_card.scss#L25)

**Comment by ArjanM83** [comment]
No, this is my custom card:

`.mdl-card-action-element {width: 900px;min-height: 0px;overflow visible;`

**Comment by ArjanM83** [comment]
No, this is my custom card:

`.mdl-card-action-element {width: 900px;min-height: 0px;overflow: visible;}`
