### ISSUE TITLE
please publish 0.0.4 to npm

### ISSUE THREAD

**Issue by jamuhl** [MEYVN-digital/mdl-selectfield#12]
great work...thanks...please publish latest version so we could use that.

**Comment by jamuhl** [comment]
never mind...just saw now that this in not mdl-selectfield published on npm...that naming is rather confusing....but API is the same...liked this one more but no npm module is not for me...

thanks anyway.

**Comment by zetta83** [comment]
@jamuhl, mdl-selectfield published on npm https://www.npmjs.com/package/mdl-select-component

**Comment by jamuhl** [comment]
nice...thanks a lot 👍
