### ISSUE TITLE
How to reset selectfield or pragramatically set a value

### ISSUE THREAD

**Issue by ramrami** [MEYVN-digital/mdl-selectfield#14]
Hi, I can't reset the selectfield nor select a value from code.

This is not working for selectfield (works for mdl textfields)
`$form[0].reset()`

This is also not working 
`$("#myselect").val("myValue");`

tks

**Comment by VadimDez** [comment]
Applies also for Angular2. When using [(ngModel)] and [value] - doesn't render selected value.

**Comment by ningliu** [comment]
I added this code , call it when you wrap it with Angular

 /**
   * Update the selected option.
   *
   * @param {string} value The value of the option which is selected.
   * @public
   */
  MaterialSelectfield.prototype.change = function(value) {
    var option = null;
    for (var i = 0; i < this.options_.length; i++) {
      option = this.options_[i];
      if (option.value === value) {
        break;
      }
    }
    if (option === null) {
      return;
    }
    this.selectedOptionValue_.textContent = option.textContent;
    option.selected = true;
  };
 
  MaterialSelectfield.prototype['change'] =
    MaterialSelectfield.prototype.change;

**Comment by mr-cpp** [comment]
Cool method! thanks
a liitle example of it's using
```document.getElementById("selectbox").MaterialSelectfield.change(id);```

**Comment by RohanAsmat** [comment]
I am using in simple HTML CSS project alongside mdl-lite ! 
It's not working with even the above provided code, any help ?

**Comment by mattjbrent** [comment]
@RohanAsmat I was having this same issue. MaterialSelectfield actually programatically wraps your elements and assigns the MaterialSelectfield object to this rather than your statically written element. try
`document.getElementById('yourElementId').parentNode.MaterialSelectfield.change(id);`

**Comment by stroobandt** [comment]
Could the use of this new `change()` method be explained in the `README.md`?
Thanks!
