### ISSUE TITLE
Head's up: Z-index issue with mdl Cards

### ISSUE THREAD

**Issue by MentalGear** [MEYVN-digital/mdl-selectfield#16]
First, let me just say: Thanks for the great plugin that you made. I'm using it on a project and it's amazing. :)
Now, here's just a heads-up for others who might get stuck in the same situation so they don't need as much time as me to figuring it out:
If one uses the dropdown on a card grid, and the card is small enough that a new card is right below where the dropdown's menu should be is, it can be that the z-index of the next mdl card is above the menu of the dropdown, effectively hiding it.

In that case, you must give your mdl card the property z-index:inherit;
Not a value, only inherit will set the z-index's to stack up correctly in that case.

**Comment by zetta83** [comment]
updated in [v0.0.7](https://github.com/MEYVN-digital/mdl-selectfield/tree/v0.0.7)

**Comment by danxfisher** [comment]
@zetta83 hey, not sure if this is still being supported but just an fyi: the z-index issue is only fixed when the slidehosw is place in the `mdl-card__actions` section.  the z-index issues still occur in the `mdl-card__supporting-text` section
