### ISSUE TITLE
select does not expand outside card (even with overflow set to visible)

### ISSUE THREAD

**Issue by ArjanM83** [MEYVN-digital/mdl-selectfield#2]
The select box does not expand outside the card where it's based on.

See my screenshot with first the select closed, on a grey card.
Then see the select opened but not expanded over the grey card.

Using a custom card:
`.mdl-card-action-element {width: 900px;min-height: 0px;overflow: visible;}`

![select](https://cloud.githubusercontent.com/assets/7382294/11347704/04f1bb2a-9223-11e5-85d4-7be65f6387f0.png)

**Comment by zetta83** [comment]
Can you post a jsfiddle.

**Comment by ArjanM83** [comment]
The issue turned out to be in the supporting-text part, this solves it:

`.mdl-card__supporting-text {overflow: visible;}`
