### ISSUE TITLE
Reinit mdl-selectfield after Ajax call

### ISSUE THREAD

**Issue by DanStorm** [MEYVN-digital/mdl-selectfield#21]
Hi, 
I imagine this is relatively simple, but I have tried a number of things to no avail.

I am using a drupal ajax callback to change options in a mdl-selectfield based on user selection of a another select on the page. When ajax refreshes the select field the javascript is not applied so the refreshed selectfield just looks like a normal select.  This is what the select looks like before ajax:

`<div id="select_content_type" class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" data-upgraded=",MaterialSelectfield"><select id="edit-content-type" name="content_type" class="form-select mdl-selectfield__select" style="opacity: 0; z-index: -1;">`

and after:

`<div id="select_content_type" class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label"><select id="edit-content-type--2" name="content_type" class="form-select error mdl-selectfield__select">`

How can I reinit after ajax completes

```
$(document).ajaxComplete(function() {
 MaterialSelectfield.init(); // what should go here
}
```
Any help greatly appreciated

**Comment by zetta83** [comment]
Hi :v:
I think that it will be useful - [Use MDL on dynamic websites](https://getmdl.io/started/index.html#dynamic)

A little more detailed:
```javascript
//before send request
const yourSelect = document.getElementById('select_content_type');
yourSelect.MaterialSelectfield.mdlDowngrade();

//after ajax completes
const yourSelect = document.getElementById('select_content_type');
componentHandler.upgradeElement(yourSelect);
```

**Comment by DanStorm** [comment]
Ah, thank you!
