### ISSUE TITLE
Move @import in selectfield.scss to a separate SASS file

### ISSUE THREAD

**Issue by leifoolsen** [MEYVN-digital/mdl-selectfield#5]
I am trying to use the mdl-selectfiled component im my own SASS workflow. 

I have installed MDL and mdl-select field with Node JS and thus MDL is located under the node_modules folder, not under '../../bower_components/material-design-lite/src/variables' as specified in selectfield.scss. This means that it is not possible for me to use selectfield.scss in my own SASS workflow. If import directives were moved to a separate file, it will be possible to use selectfield.scss in any SASS workflow.

As a workaround, I've copied selectfield.scss into my own project and removed the import directives. This works great, but it would be best to use the component directly.

**Comment by leifoolsen** [comment]
A SASS variable for the roo path would have been preferable, but that's not possible in SASS, see: https://github.com/sass/sass/issues/739

If you use webpack, then you can prefix import path with "~", as suggested here: https://github.com/webpack/css-loader/issues/12

- regards

**Comment by zetta83** [comment]
@leifoolsen, please check
