### ISSUE TITLE
Incompatible with the latest mdl release

### ISSUE THREAD

**Issue by gpgekko** [MEYVN-digital/mdl-selectfield#7]
When used together with the latest MDL release, I get the following JS error:

> selectfield.js:407 Uncaught ReferenceError: componentHandler is not defined(anonymous function) 

(here's a fiddle with the updated libraries: http://jsfiddle.net/gpgekko/mofbbamo/13/)

**Comment by zetta83** [comment]
it is a problem with the script load order.
important MDL must be loaded before mdl-selectfield
here's a fiddle updated http://jsfiddle.net/mofbbamo/14/
